export { connectMongo, disconnectMongo } from "./connection"
export { MenuModel, type IMenuDocument } from "./models/menu"
export { LocationModel, type ILocationDocument } from "./models/location"
export { SyncOrderModel, type SyncOrderDocument } from "./models/sync-order"
export { CashSaleEventModel, type CashSaleEventDocument } from "./models/cash-sale-event"
export { ZReportRecordModel, type ZReportRecordDocument } from "./models/z-report-record"
export { UserModel } from "./models/user"
export { ConsumerModel } from "./models/consumer"
export { TenantModel } from "./models/tenant"

// ── Inventory (FASE04 — Event Ledger + Estado derivado) ──────────────────────
export { InventorySKUModel, type IInventorySKUDocument } from "./models/inventory-sku"
export { InventoryStorageLocationModel, type IInventoryStorageLocationDocument } from "./models/inventory-storage-location"
export { InventoryUnitEquivalenceModel, type IInventoryUnitEquivalenceDocument } from "./models/inventory-unit-equivalence"
export { InventoryRecipeModel, type IInventoryRecipeDocument } from "./models/inventory-recipe"
export { InventoryLedgerModel, type IInventoryEventDocument } from "./models/inventory-ledger"
export { InventoryStateModel, type IInventoryStateDocument } from "./models/inventory-state"
export { InventoryStateSnapshotModel, type IInventoryStateSnapshotDocument } from "./models/inventory-state-snapshot"
export { InventorySkuMenuLinkModel, type IInventorySkuMenuLinkDocument } from "./models/inventory-sku-menu-link"
